name:                lambda-machine
version:             0.1.0.0
github:              "commelina/lambda-machine"
license:             BSD3
author:              "Commelina"
maintainer:          "maosics@gmail.com"
copyright:           "2020 Commelina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/commelina/lambda-machine#readme>

dependencies:
- base >= 4.7 && < 5
- clash-prelude
- clash-lib
- ghc-prim
- lens
- pretty

library:
  source-dirs: src


#executables:
#  clash-proj-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - clash-proj

tests:
  clash-proj-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clash-proj
    - process
